### ISSUE TITLE
Charts overflowing outside divs while flash message is displayed

### ISSUE THREAD

**Issue by jtlindsey** [jtlindsey/RailsFinance#2]
Chartkick charts overflowing outside divs while flash message is displayed. Charts return to correct size/within div as soon as flash message is closed (clicking x) or page is reloaded. Reproducible on main page after login.

**Comment by jtlindsey** [comment]
Issue doesn't appear to be present when fixed-panel-height css is adjusted
```html
<div class="panel-body fixed-panel-height">
```
css from:
```css
@media screen and (min-width: 480px) {
  .fixed-panel-height {
    height: 270px;
    padding: 2px;
    margin: 2px;
  }
}
```
to
```css
@media screen and (min-width: 480px) {
  .fixed-panel-height {
    height: 270px; 
    padding-top: 2px; 
    padding-bottom: 2px;

    padding-left: auto;
    padding-right: auto;
  }
}
```
